controller_names:
  - joint_trajectory_controller
  - hand_controller

joint_trajectory_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - fer_joint1
    - fer_joint2
    - fer_joint3
    - fer_joint4
    - fer_joint5
    - fer_joint6
    - fer_joint7

hand_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints:
    - fer_finger_joint1
